# -*- coding: utf-8 -*-
"""23 oct .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dmyuZlvWqQAuMU4LkQ0jIelO9hhXTzBm
"""

#dictionary
# keys and value
#ordered
#no index
#mutable in nature
#Dictionary
# key and valur pairs
# hashmap
# key unique
# value can be unique or not
# ordered
# no index
# mutuable in nature {}
my_dictionary={10:"tushar",20:"naina",}
len(my_dictionary)
my_dictionary.keys()
my_dictionary.values()
my_dictionary.items()
my_dictionary[10]='ajay sharma'

my_dictionary={10:"tushar",20:"naina"}
len(my_dictionary)

my_dictionary.keys()

my_dictionary.values()

my_dictionary[10]='tushar goyal'
print(my_dictionary)

my_dictionary.items()

mydictionary={10:"tushar",20:"naina"}
mydictionary[10]
for x in mydictionary:
  print(x,mydictionary[x])

mydictionary={"x":10}
mydictionary["x"]=mydictionary["x"]+2
print(mydictionary)

# loop => 10,18
mydictionary={"total":0}
for x in range(10,19):
  mydictionary["total"]=mydictionary["total"]+1
print(mydictionary)

#"heyuser"
mydictionary={"total":0}
for x in "heyuser":
  mydictionary["total"]=mydictionary["total"]+1
print(mydictionary)

mydictionary={"total":0}
for x in "heyuser":
  mydictionary[x]=1
print(mydictionary)

mydictionary={"total":5}
if "total" not  in mydictionary:
  mydictionary["total"]=1
else:
  mydictionary ["total"]=mydictionary["total"]+1
print(mydictionary)

mydictionary={"total":0}
for x in "heyuser":
  if x not in mydictionary:
    mydictionary[x]=1
  else:
    mydictionary[x]=mydictionary[x]+1
print(mydictionary)

mydictionary={"total":0}
count=0
for x in "heyuser":
  count+=1
print(count)

dictionary={'yes':0,"no":0}
for i in range(1,51):
  if i%2 == 0 and i%7 == 0:
    dictionary['yes']=dictionary['yes']+1
  else:
    dictionary['no']=dictionary['no']+1
print(dictionary)

string="hey hello tushar aei"
dict={"vowels":0, "consonant":0 }
for i in string:
  if i in "aeiouAEIOU":
    dict["vowels"]=dict["vowels"]+1
  else:
    dict["consonant"]=dict["consonant"]+1
print(dict)

"hey hello".split( )

"hey hello".split("e")

x="hey hello".split( )
for i in x:
  print(i)

#set=>

#collection of element
#unique
#unordered
#no index
#set are mutable but set element are immutable

myset={10,20,30,40,20,30,30,20}
print(myset)

myset.add(658)
print(myset)

myset.remove(40)
print(myset)

myset.discard(60)
print(myset)