# -*- coding: utf-8 -*-
"""python tutorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xnAaim5fi6tcDzejeT9ysiQGToVRId-y
"""

def longest(words):
  if not words:
    return " "
  prefix = words[0]

  for i in words[1:len(words)]:
    while not i.startswith(prefix):
      prefix = prefix[0:-1]
      if not prefix:
        return " "
  return prefix

words=['apple','apricot','apology']
print(longest(words))

!pip install pyjokes

import pyjokes
joke = pyjokes.get_joke()
print(joke)

a = 1       # a is variable like container
b = 2
print(a+b)

a=1
print("a is :" ,type(a))
b='gaurav'
print("b is :" ,type(b))
c=7.4
print("c is :" ,type(c))
d=True
print("d is :" ,type(d))

# comparision operator  --> return boolean value

d = 5>4
print(d)

# Truth table of or operator
print("True or False is :" , True or False )
print("True or True is :" , True or True )
print("False or True is :" , False or True )
print("False or False is :" , False or False )

# Truth table of and operator
print("True and False is :" , True and False )
print("True and True is :" , True and True )
print("False and True is :" , False and True )
print("False and False is :" , False and False )

# add two number
a=1
b=5
print(a+b)

# Remainder
a = 34
b = 5
print('reminder when a is divide by b is :',a%b)

# user input
a = input('Enter the value of a :')
print(type(a))

# a > b or not
a = int(input('Enter the number 1 : '))
b = int(input('Enter the number 2 : '))
print("a is greater than b : ", a>b)

# Avg of two number
a = int(input('Enter the number 1 : '))
b = int(input('Enter the number 2 : '))
print("The avg of these two number is : ", (a+b)/2)

a = int(input('Enter the number 1 : '))

print("The square of number is : ", a**2)

s = 'name'
print(len(s))

s[1:3]

name = "harry"
nameshort = name[0:3]
print(nameshort)
character1 = name[1]
print(character1)
print(name[-4:-1])
print(name.endswith('rry'))
print(name.capitalize())

name = input("Enter your name : ")
print(f"Good Afternoon {name}")

letter = '''Dear <|Name|>,
            You are selected!
            <|Date|> '''

print(letter.replace("<|Name|>","Gaurav")
      .replace("<|Date|>","24 Sept 2050"))

name = 'Harry is a good  boy  and  '
print(name.find('  ')) # double space find
print(name.find('goo'))  # find - index find krta h

name = 'Harry is a good  boy  and  '
print(name.replace('  ',' '))

letter = "Dear Harry, this is python course is nice. Thanks!"
print(letter)
letter = "Dear Harry,\n\tThis is python course is nice.\nThanks!"
print(letter)
print(letter[0])

friends = ['Apple','Orange',12,321.32,'Aakash','Rohan',False]
print(friends[0])
friends[0]='Grapes'
print(friends[0])

friends.append('Harry')
print(friends)

l1=[1,34,54,2,11]
l1.sort()
print(l1)
l1.reverse()
print(l1)

l1.insert(3,333)
print(l1)

l1.pop(2)
print(l1)
l1.pop()
print(l1)

fruits = []
f1=input('Enter the fruit name : ')
fruits.append(f1)
f2=input('Enter the fruit name : ')
fruits.append(f2)
f3=input('Enter the fruit name : ')
fruits.append(f3)
f4=input('Enter the fruit name : ')
fruits.append(f4)
f5=input('Enter the fruit name : ')
fruits.append(f5)
f6=input('Enter the fruit name : ')
fruits.append(f6)
f7=input('Enter the fruit name : ')
fruits.append(f7)
print(fruits)

marks = []
f1=int(input('Enter the marks here : '))
marks.append(f1)
f2=int(input('Enter the marks here : '))
marks.append(f2)
f3=int(input('Enter the marks here : '))
marks.append(f3)
f4=int(input('Enter the marks here : '))
marks.append(f4)
f5=int(input('Enter the marks here : '))
marks.append(f5)
f6=int(input('Enter the marks here : '))
marks.append(f6)
f7=int(input('Enter the marks here : '))
marks.append(f7)
marks.sort()
print(marks)

a = (34,323,'Harry')
print(a)

l=[23,43,643,123]
print(sum(l))

l=[230,4330,643,123,0,0,0]
n = l.count(0)
print(n)

marks={
    "Harry":100,
    "Gaurav":99,
    "Rohan":23
}
print(marks , type(marks))
print(marks["Gaurav"])

print(marks.items())

print(marks.values())

print(marks.keys())

marks.update({"Harry":99,"Renuka":100})
print(marks)

print(marks.get('Harry'))

print(marks.pop("Harry"))

print(marks.popitem())

s = {1,5,8}
print(s)

s=set()  # don`t use s={} as it will create an empty dictionary
print(type(s))

# Add
s.add(566)
print(s)
s.remove(1)
print(s)

# Union
s1={1,4,2,5}
s2={1,4,3,7,5}
print(s1.union(s2))
print(s1.intersection(s2))
print(s1.difference(s2))
print(s1.symmetric_difference(s2))

print(s1.issubset(s2))
print(s2.issubset(s1))

A = {1, 2, 3}
B = {1, 2, 3, 4, 5}
C = {6, 7, 8}

# Subset Check
print(A.issubset(B))  # True, because all elements of A are in B
print(B.issubset(A))  # False, because B has extra elements

# Superset Check
print(B.issuperset(A))  # True, because B contains all elements of A
print(A.issuperset(B))  # False, because A does not contain all elements of B

# Disjoint Check
print(A.isdisjoint(C))  # True, because A and C have no elements in common
print(A.isdisjoint(B))  # False, because A and B share elements

words = {
    "madad":"Help",
    "Kursi":"Chair",
    "Billi":"Cat"
}
word = input("Enter the word you want meaning of : ")
print(words[word])

k=set()
n=int(input("ENter number : "))
k.add(int(n))
n=int(input("ENter number  : "))
k.add(int(n))
n=int(input("ENter number  : "))
k.add(int(n))
n=int(input("ENter number  : "))
k.add(int(n))
n=int(input("ENter number  : "))
k.add(int(n))
n=int(input("ENter number  : "))
k.add(int(n))
n=int(input("ENter number  : "))
k.add(int(n))
n=int(input("ENter number  : "))
k.add(int(n))
print(k)

s = set()
s.add(18)
s.add("18")
print(s)

s=set()
s.add(20)
s.add(20.0)
s.add("20")
print(s)
print(len(s))

s={}
print(type(s))

d = {}
name=input("Enter friends name : ")
lang = input("Enter language name : ")
d.update({name: lang})
name=input("Enter friends name : ")
lang = input("Enter language name : ")
d.update({name : lang})
name=input("Enter friends name : ")
lang = input("Enter language name : ")
d.update({name : lang})
name=input("Enter friends name : ")
lang = input("Enter language name : ")
d.update({name : lang})
print(d)

s = {8,7,12,"Harry",[1,2]}
# Not update because we can not add list in set and not use indexed

# Rotating array
list1=[1,2,3,4,5]
n=int(input('Enter the number : '))
size1=len(list1)
n=n%size1
mylist=[0]*size1
for index in range(len(list1)):
  total = (index+n)%size1
  mylist[total]=list1[index]
print(mylist)

a1 = int(input("Enter number 1 : "))
a2 = int(input("Enter number 2 : "))
a3 = int(input("Enter number 3 : "))
a4 = int(input("Enter number 4 : "))

if(a1>a2 and a1>a3 and a1>a4):
  print("a1 is greatest number :",a1)
elif(a2>a3 and a2>a1 and a2>a4):
  print("a2 is greatest number :",a2)
elif(a3>a1 and a3>a2 and a3>a4):
  print("a3 is greatest number : ",a3)
else:
  print("a4 is greatest number :",a4)

marks1 = int(input("Enter marks 1 : "))
marks2 = int(input("Enter marks 2 : "))
marks3 = int(input("Enter marks 3 : "))

# check if total prcentage
total_percentage = (100*(marks1 + marks2 + marks3))/300

if (total_percentage>40 and marks1 >=33 and marks2 >=33 and marks3>=33):
  print("You are Passed",total_percentage)
else:
  print("You Failed",total_percentage)

p1 = 'Make a lot of money'
p2 = 'buy now'
p3 = 'subscribe this'
p4 = 'click this'

message = input("Enter your comment : ")

if ((p1 in message) or (p2 in message) or (p3 in message) or (p4 in message)):
  print("This comment in a spam")
else:
  print("This comment is not a spam")

username = input("Enter user name : ")
if (len(username)<10):
  print("Your username contain less than 10 character")
else:
  print('more than 10 character')

l = ['harry','rohan','suhani','divya']
name = input("Enter the name : ")
if name in l:
  print("Your name is in the list")
else:
  print("Your name is not in the list")